fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm

    service:
        user_manager: sonata.user.orm.user_manager
    profile:  # Authentication Form
        form:
            type:               fos_user_profile
            handler:            fos_user.profile.form.handler.default
            name:               fos_user_profile_form
            validation_groups:  [Authentication] # Please note : this is not the default value
sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    class:
        user:         Application\Sonata\UserBundle\Entity\User
        group:        Application\Sonata\UserBundle\Entity\Group
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.user.block.menu:     # used to display the menu in profile pages
        sonata.user.block.account:
        sonata.block.service.text:
        sonata.admin.block.search_result:
sonata_media:
    #TODO: after php 5.6.7-1, openssl 1.0.2a and ssl-cert 1.0.36. you don't need this anymore.
    # see : https://github.com/sonata-project/SonataMediaBundle/issues/759
    class:
        media:              Application\Sonata\MediaBundle\Entity\Media
        gallery:            Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media:  Application\Sonata\MediaBundle\Entity\GalleryHasMedia
    buzz:
        connector:  sonata.media.buzz.connector.curl
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    cdn:
        server:
            path: "%sonata.cdn.server%"
    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
    contexts:
        default:  # the default context is mandatory
            download:
                strategy: sonata.media.security.superadmin_strategy
                mode: http
            providers:
                - sonata.media.provider.image
            formats:
                small:   { width: 400,  quality: 70}
                medium:  { width: 800,  quality: 70}
                large:   { width: 1170, quality: 70}
    providers:
        image:
            service:    sonata.media.provider.image
            filesystem: sonata.media.filesystem.local
            cdn:        sonata.media.cdn.server
            generator:  sonata.media.generator.default
            thumbnail:  sonata.media.thumbnail.format
            allowed_extensions: ['jpg', 'png', 'jpeg']
            allowed_mime_types: ['image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png']
sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
    title: Hao TAN
    options:
        html5_validate: false # does not use html5 validation
        pager_links: 5 # pager max links to display
    templates:
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        # default value if done set, actions templates, should extends a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
        #edit:    KreactiveOrientationBackOfficeBundle:Form:edit.html.twig
    dashboard:
        groups:
            admin.group.user:
                label: admin.group.user
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
            admin.group.media:
                label: Media
                items:
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery