parameters:
    sonata.media.admin.media.class: Application\Sonata\MediaBundle\Admin\ORM\MediaAdmin
    sonata.media.admin.media.controller: ApplicationSonataMediaBundle:MediaAdmin
services:
    sonata.media.resizer.outbound:
        class: Application\Sonata\MediaBundle\Resizer\OutBoundResizer
        arguments: [@sonata.media.adapter.image.gd, 'outbound', @sonata.media.metadata.proxy]